- type: latheRecipe
  id: MagazineMagnumEmpty
  result: MagazineMagnumEmpty
  category: Ammo
  completetime: 5
  materials:
    Steel: 50

- type: latheRecipe
  id: MagazineMagnum
  result: MagazineMagnum
  category: Ammo
  completetime: 5
  materials:
     Steel: 210

- type: latheRecipe
  id: ClothingShoesBootsMagCom
  result: ClothingShoesBootsMagCom
  completetime: 10
  materials:
    Steel: 1000
    Plastic: 500
    Silver: 250
