- type: latheRecipe
  id: MagazineMagnumEmpty
  result: MagazineMagnumEmpty
  category: Ammo
  completetime: 5
  materials:
    Steel: 50

- type: latheRecipe
  id: MagazineMagnum
  result: MagazineMagnum
  category: Ammo
  completetime: 5
  materials:
     Steel: 210

- type: latheRecipe
  parent: ClothingShoesBootsMagSci
  id: ClothingShoesBootsSecurityMagboots
  result: ClothingShoesBootsSecurityMagboots
  materials:
     Steel: 1000
     Plastic: 500
